diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
user.name=mary-mtrf
user.email=masha_wade@mail.ru
http.https://gitlab.albank.ru.sslcert=C:/sert/gabyshev_at.crt
http.https://gitlab.albank.ru.sslkey=C:/sert/gabyshev_at.key
http.https://gitlab.albank.ru.sslverify=false
http.https://gitlab.albank.ru.sslcertpasswordprotected=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.popo4ka.url=https://github.com/mary-mtrf/angular_weather.git
remote.popo4ka.fetch=+refs/heads/*:refs/remotes/popo4ka/*
